# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{google_analytics_plugin}
  s.version = "0.3.0-beta"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eric Davis"]
  s.date = %q{2012-09-02}
  s.description = %q{Redmine plugin to insert a Google Analytics (or e.g. Piwik) tracking code into Redmine based on user roles.}
  s.email = %q{edavis@littlestreamsoftware.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "COPYRIGHT.txt",
     "CREDITS.txt",
     "GPL.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "app/views/settings/_google_analytics_settings.html.erb",
     "config/locales/de.yml",
     "config/locales/en.yml",
     "config/locales/hu.yml",
     "config/locales/it.yml",
     "config/locales/ja.yml",
     "init.rb",
     "lib/google_analytics_hooks.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{https://projects.littlestreamsoftware.com/projects/TODO}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{google_analytics_plugin}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Redmine plugin to insert a Google Analytics (or e.g. Piwik) tracking code into Redmine based on user roles.}
  s.test_files = [
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
